language: cpp
dist: trusty

matrix:
  include:
    - compiler: clang
      addons:
        apt:
          sources: 
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty
          packages:
            - clang
            - cmake
            - libboost-system-dev
            - libboost-regex-dev

    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc
            - cmake
            - libboost-system-dev
            - libboost-regex-dev

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
